services:
  - type: web
    name: url-shortener-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://4lperez:xTYNZ4J3bNZ3LkYp@cluster0.khcfjlw.mongodb.net/myDatabase?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 2d794a30948c84bd6cc36b178de00fa5233dcb01d22734d262999898d5b84b63
      - key: PORT
        value: 5000
